services:
  backend:
    build: 
      context: ./server/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3001:3001
      - 4000:4000
  app:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend