const SUCCESS_CODE_STATUS = 200;
const CREATED_CODE_STATUS = 201;
const BAD_REQUEST_CODE_STATUS = 400;
const UNAUTHORIZED_CODE_STATUS = 401;
const FORBIDDEN_CODE_STATUS = 403;
const NOT_FOUND_CODE_STATUS = 404;
const INTERNAL_SERVER_ERROR_CODE_STATUS = 500;

const JWT_SECRET = process.env.JWT_SECRET ?? "default-secret";

const MAX_HEALTH = 10;
const DAMAGE = 1;
const MAX_PLAYERS = 2;

export default {
  SUCCESS_CODE_STATUS,
  CREATED_CODE_STATUS,
  BAD_REQUEST_CODE_STATUS,
  NOT_FOUND_CODE_STATUS,
  INTERNAL_SERVER_ERROR_CODE_STATUS,
  UNAUTHORIZED_CODE_STATUS,
  FORBIDDEN_CODE_STATUS,
  JWT_SECRET,
  MAX_HEALTH,
  DAMAGE,
  MAX_PLAYERS,
};
